# ========================================
# Oracle Database
# ========================================

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.config.import=optional:file:.env[.properties]
KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}

# ========================================
# JPA
# ========================================

# Oracle 데이터베이스에 맞는 SQL 문법 사용
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 실행되는 SQL을 콘솔에 출력
spring.jpa.show-sql=true

# SQL을 보기 좋게 정렬
spring.jpa.properties.hibernate.format_sql=true

# 개발 중에는 테이블을 자동으로 변경하지 않음
spring.jpa.hibernate.ddl-auto=validate